---
  environment: production
  chdir: /Users/andrewevans/Sites/Sinatra/HackerMusic
  address: 127.0.0.1
  user: andrewevans
  group: 
  port: 4567
  pid: /Users/andrewevans/Sites/Sinatra/HackerMusic/thin.pid
  rackup: /Users/andrewevans/Sites/Sinatra/HackerMusic/rackup_hm.ru
  log: /Users/andrewevans/Sites/Sinatra/HackerMusic/logs/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true